#Dataset from LendingClubs.com (2007-2010)
loans <- read.csv("/Users/satyamaddali/Desktop/R for data science/R-Course-HTML-Notes/R-for-Data-Science-and-Machine-Learning/Training Exercises/Machine Learning Projects/CSV files for ML Projects/loan_data.csv")
summary(loans)
str(loans)
loans$inq.last.6mths <- factor(loans$inq.last.6mths)
factor(inq.last.6mths)
loans$delinq.2yrs <- factor(loans$delinq.2yrs)
loans$pub.rec <- factor(loans$pub.rec)
loans$not.fully.paid <- factor(loans$not.fully.paid)
factor(not.fully.paid)
loans$credit.policy <- factor(loans$credit.policy)
#Data Exploration
library(ggplot2)
print(ggplot(loans,aes(fico))+geom_histogram(aes(fill = factor(not.fully.paid)),color= 'black'))
print(ggplot(loans,aes(purpose))+geom_bar(aes(fill= factor(not.fully.paid)), color= 'black', position = 'dodge'))
print(ggplot(loans,aes(x= int.rate, y=fico)) + geom_point(aes(fill= factor(not.fully.paid))))
#Building the model
library(caTools)
set.seed(101)
model <- sample.split(loans$not.fully.paid, SplitRatio = 0.7)
train <- subset(loans, model == T)
test <- subset(loans, model == F)
#Installing packages for SVM
install.packages('e1071')
library(e1071)
library(data.table)
#Using SVM to train and test
model.builds <- svm(not.fully.paid ~ ., data = train)
summary(model.build)
model.pred <- predict(model.builds,test[1:13])
table(model.pred,test$not.fully.paid)
#Tuning the model
tune.results <- tune(svm,train.x=not.fully.paid ~ ., data=train,kernel='radial',ranges=list(cost=c(1,10), gamma=c(0.1,1)))
model.builds <- svm(not.fully.paid ~ ., data = train, cost=10,gamma=0.1)
summary(model.build)
model.pred <- predict(model.builds,test[1:13])
table(model.pred,test$not.fully.paid)
